### PR TITLE
UCHAT-121 slightly enlarge emojis

### PR DESCRIPTION
**Pull request by erikgui**
Small change to slightly enlarge emojis as there's numerous complains about emojis being too small.
Before:
screen shot 2017-01-03 at 4 51 57 pm
After:
screen shot 2017-01-03 at 4 48 38 pm

### CODE REVIEW

**Comment by csduarte** [comment]
Does this have any odd effects on multi line text that is mixed with emoji?

**Comment by dmeza** [comment]
@csduarte It looks good to me:

uchat-largeremojis-bigscreen
uchat-largeremojis-smallscreen
uchat-largeremojis-mobile

**Comment by csduarte** [comment]
An yes, thank you for the screenshots, but that confirms my worries. Notice the lines without emoji, they spacing is off. I've sent the screen shot to nayong. 

I'd consider just raising the line-height, but that can give inputs trouble and style issues.

**Comment by erikgui** [comment]
Slack sets the emoji as 22x22:
screen shot 2017-01-04 at 10 06 59 am

Currently on production, our emoji appears as such:
screen shot 2017-01-04 at 10 17 35 am

I am trying to understand why production emoji is currently 1.6em, as it's defined as 1.5em in the css.

**Comment by erikgui** [comment]
Increasing our emoji size to `1.6em` would result in almost similar size as slack's emojis:
screen shot 2017-01-04 at 10 47 32 am

Comparing 1.5em to 1.6em we can see there's no line spacing changes:

1.5em (current):
screen shot 2017-01-04 at 10 45 55 am

1.6em:
screen shot 2017-01-04 at 10 45 31 am

It seems like modifying to 1.6em wouldn't be as impactful as changing to 1.8em.

**Pull request merged**
