### PR TITLE
UCHAT-144 Increase max length of channel names

### PR DESCRIPTION
**Pull request by thopki1**

### CODE REVIEW

**Comment by dmeza** [comment]
@thomchop @csduarte  I tried different emojis and text combinations, different browsers. It does work well. It restricts the channel to the right amount of characters in the database and of course if an emoji is not complete it just displays those characters. I think this PR is working well.
Besides any problem with emojis or non-basic characters would happen right now already.
Ticket: https://jira.uberinternal.com/browse/UCHAT-144

uchat-emojisinchanneltitle

**Comment by csduarte** [comment]
Are there no required backend changes?

**Comment by DMezaUber** [comment]
@csduarte sorry, hadn't seen your comment. 
No changes needed on the backend. The channel name is already a varchar(64) in the database:
| Name          | varchar(64)  | YES  | MUL | NULL    |       |
An that's the max length set as a constant for these changes:
CHANNELS_MAX_LENGTH_NAME: 64

**Comment by csduarte** [comment]
Merged into private repo mattermost-platform-shift/pull/9

**Pull request closed without merging**
