### PR TITLE
UCHAT-181 Add button to DM a user from their profile preview popover tile

### PR DESCRIPTION
**Pull request by dmeza**
Ticket:
https://jira.uberinternal.com/browse/UCHAT-181

uchat-181-newmessagebtn
uchat-181-newmessagebtn-2

### CODE REVIEW

**Comment by thomchop-uber** [comment]
@dmeza Instead of having both a plain text mailto link and a message button, we decided to use icon buttons for these two actions in the popover tile. So we should replace the link & button with the icons that Nayong attached to the jira ticket for UCHAT-318. (These are custom icons that will be used in the points-of-contact buttons in the (forthcoming) profile details sidebar that Nayong has designed.)

**Comment by DMezaUber** [comment]
Changes from: https://jira.uberinternal.com/browse/UCHAT-318 to add icons for Email and DM.

uchat-181-iconsforemail-dm
uchat-181-iconsforemail-dm-small

**Comment by DMezaUber** [comment]
Added a link to whober from the user name. It's a version for: https://jira.uberinternal.com/browse/UCHAT-76
uchat-76-linktowhober

**Comment by dmeza** [comment]
Refactored Profile Popover to be a separate component and added new design based on ticket: 
`UCHAT-342 Redesign profile hovercard to match whober style spec` https://jira.uberinternal.com/browse/UCHAT-342

This is the style change:
hover card- desktop 1

Results:
uchat-342_redesignprofilehovercard-dark-v2
uchat-342_redesignprofilehovercard-light-v2

@thomchop @erikgui please help me review it

**Pull request merged**
